// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Adventures.Model.Models;
using Microsoft.EntityFrameworkCore;

namespace Adventures.Data.Interfaces
{
    public interface ITripleStoreContext
    {
        DbSet<RdfTriple> RdfTriples { get; set; }
    }
}