// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Adventures.Model.Models;

public partial class RdfTriple
{
    public string Id { get; set; }

    public string Subject { get; set; }

    public string Predicate { get; set; }

    public string Object { get; set; }

    public byte[] Data { get; set; }
}