// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Adventures.Model.Models;

public partial class VShortGuid
{
    public string SubstrUuid08SubstrUuid84SubstrUuid124SubstrUuid16 { get; set; }
}