// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Adventures.Data.Interfaces;
using Microsoft.EntityFrameworkCore;

namespace Adventures.Model.DataSource;

public partial class TripleStoreContext : DbContext, ITripleStoreContext
{

}