// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Adventures.Model.Models;
using Microsoft.EntityFrameworkCore;

namespace Adventures.Model.DataSource;

public partial class TripleStoreContext : DbContext
{
    public TripleStoreContext()
    {
    }

    public TripleStoreContext(DbContextOptions<TripleStoreContext> options)
        : base(options)
    {
    }

    public virtual DbSet<RdfTriple> RdfTriples { get; set; }

    public virtual DbSet<VShortGuid> VShortGuids { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlite("Data Source=X:\\Blog-API\\Adventures.Model\\DataSource\\TripleStore.db");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<RdfTriple>(entity =>
        {
            entity.Property(e => e.Subject).IsRequired();
        });

        modelBuilder.Entity<VShortGuid>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("v_shortGuid");

            entity.Property(e => e.SubstrUuid08SubstrUuid84SubstrUuid124SubstrUuid16).HasColumnName("SUBSTR(UUID, 0, 8)||'-'||SUBSTR(UUID,8,4)||'-'||SUBSTR(UUID,12,4)||'-'||SUBSTR(UUID,16)");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}