// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using blogapi.Context;

#nullable disable

namespace blogapi.Migrations
{
    [DbContext(typeof(BloggingContext))]
    [Migration("20241030021604_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("blogapi.Context.Triple", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Object")
                        .HasMaxLength(254)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Predicate")
                        .HasMaxLength(254)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasMaxLength(254)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Value")
                        .HasColumnType("BLOB");

                    b.HasKey("Id")
                        .HasName("PK_Triples_Id");

                    b.HasIndex(new[] { "Subject", "Predicate", "Object" }, "IX_TriplesSubPredObj")
                        .IsUnique();

                    b.HasIndex(new[] { "Object" }, "IX_Triples_Object");

                    b.HasIndex(new[] { "Predicate" }, "IX_Triples_Predicate");

                    b.HasIndex(new[] { "Subject" }, "IX_Triples_Subject");

                    b.ToTable("Triples");
                });

            modelBuilder.Entity("blogapi.Context.TriplesCrossRef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChildId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TripleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ChildId" }, "IX_TriplesCrossRef_ChildId");

                    b.HasIndex(new[] { "ParentId" }, "IX_TriplesCrossRef_ParentId");

                    b.HasIndex(new[] { "TripleId" }, "IX_TriplesCrossRef_TripleId");

                    b.ToTable("TriplesCrossRef", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
