// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace Adventures.Model.Models
{
    public interface IRdfTriple
    {
        byte[] Data { get; set; }
        string Id { get; set; }
        string Object { get; set; }
        string Predicate { get; set; }
        string Subject { get; set; }
    }
}